### ISSUE TITLE
Predictably random cron time thing isn't working correctly

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/module-standardiser#36]
The last time I ran standardiser, it started affecting the cron times for a bunch of workflows. That's supposed to be predictable and never change when we run it subsequently.

example affected PRs:
- https://github.com/silverstripe/cwp-starter-theme/pull/242
- https://github.com/silverstripe/cwp-watea-theme/pull/178

## Related issues
https://github.com/silverstripe/module-standardiser/issues/20

**Comment by emteknetnz** [comment]
I think there's no actually not a bug - looking at the commits looks based on the commit messages it like those workflow files were added manually, rather than module-standardiser - https://github.com/silverstripe/cwp-starter-theme/commit/edbd2a8a01e013fcde1d249e849a9d0c0c90ee08 - https://github.com/silverstripe/cwp-watea-theme/commit/83c8b4644badabe6910b3dcd0fe30bc321ddbde3 i.e. they have `MNT Use gha-dispatch-ci ` instead of `MNT Run module-standardiser`

I've attached a PR to fix the related issue

**Comment by GuySartorelli** [comment]
Hopefully we remember you discovered that next time we run standardiser 😅
